/**
 * Replace all local /images/... paths in source code with Cloudinary URLs.
 * 
 * Uses the mapping from scripts/image-map.json (generated by upload-to-cloudinary.ts)
 *
 * Usage: npx tsx scripts/replace-image-urls.ts
 */

import * as fs from "fs";
import * as path from "path";

const MAP_FILE = path.join(process.cwd(), "scripts", "image-map.json");

// Files to update
const SOURCE_FILES = [
  "src/lib/products.ts",
  "src/lib/categories.ts",
  "src/lib/packages.ts",
  "src/lib/serverDb.ts",
  "src/lib/adminData.ts",
];

function main() {
  if (!fs.existsSync(MAP_FILE)) {
    console.error("❌ image-map.json not found! Run upload-to-cloudinary.ts first.");
    process.exit(1);
  }

  const mapping: Record<string, string> = JSON.parse(fs.readFileSync(MAP_FILE, "utf-8"));
  const entries = Object.entries(mapping);

  console.log(`\n📝 Loaded ${entries.length} URL mappings from image-map.json\n`);

  let totalReplacements = 0;

  for (const relPath of SOURCE_FILES) {
    const filePath = path.join(process.cwd(), relPath);

    if (!fs.existsSync(filePath)) {
      console.log(`  ⏭️  Skipping ${relPath} (file not found)`);
      continue;
    }

    let content = fs.readFileSync(filePath, "utf-8");
    let fileReplacements = 0;

    for (const [localPath, cloudUrl] of entries) {
      // Count occurrences
      const regex = new RegExp(escapeRegex(localPath), "g");
      const matches = content.match(regex);

      if (matches) {
        content = content.replace(regex, cloudUrl);
        fileReplacements += matches.length;
      }
    }

    if (fileReplacements > 0) {
      fs.writeFileSync(filePath, content);
      console.log(`  ✅ ${relPath} — ${fileReplacements} URL(s) replaced`);
      totalReplacements += fileReplacements;
    } else {
      console.log(`  ⏭️  ${relPath} — no local image paths found`);
    }
  }

  console.log(`\n✨ Done! Replaced ${totalReplacements} image URL(s) across ${SOURCE_FILES.length} files.`);
  console.log(`\n👉 Next steps:`);
  console.log(`   1. Review the changes: git diff`);
  console.log(`   2. Commit: git add -A && git commit -m "chore: migrate images to Cloudinary"`);
  console.log(`   3. Push: git push`);
  console.log(`   4. Seed DB: visit your-app.vercel.app/api/seed\n`);
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

main();
